### ISSUE TITLE
Refactor CMake to support builds with different vendor specific GPU codes

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#160]
Currently, HiOp CMake assumes GPU == CUDA. Furthermore, when GPU is enabled, some CUDA specific libraries are required. To add support for AMD GPUs and be able to extend this to Intel GPUs, the CMake should implement following logic:
1. When setting `HIOP_USE_GPU`:
    - Once this flag is set to `On` user should be presented choice of selecting _either_ CUDA _or_ HIP. (We should eventually support the mixture of the two, but for now, this should suffice.)
        - If CUDA is selected `HIOP_USE_MAGMA` is set to `On`. 
            - This should stay like this until there is a configuration option to disable building dense and MDS solvers.
            - If `HIOP_SPARSE` is `On`, then `HIOP_USE_STRUMPACK` is set to `On`, as well.
            - If neither Magma nor Strumpack are found, CMake should send back message that CUDA support is not enabled and turn it off.
        - If HIP is selected `HIOP_USE_HIPMAGMA` is set to `On`.
            - The rest of the logic should be similar as for the CUDA case.
        - Leave a placeholder for Intel GPU selection.
        - If neither CUDA nor HIP support are available, the CMake should return message to that end and turn `HIOP_USE_GPU` off.
     - If GPU support is off, then no options for choosing CUDA or HIP should be visible to the user.
     - RAJA/Umpire selection should be independent of GPU support selection.
2. It is user's responsibility to provide RAJA and Umpire dependencies with support for user's hardware.
    - Per @davidbeckingsale separate RAJA and Umpire libraries should be built (and expected by CMake) for CUDA, HIP and OpenMP support.

CC @ashermancinelli @cnpetra @nychiang @rothpc @nkoukpaizan

**Comment by cnpetra** [comment]
lgtm

**Comment by nkoukpaizan** [comment]
I have a question. Since the `HIOP_SPARSE` logic is contingent on the CUDA/HIP selection, does that mean that there are no plans to use `STRUMPACK` on the CPU, or would there be another GPU-agnostic logic that is not discussed here because we are focusing on the backend selection?

**Comment by nychiang** [comment]
I think the logic is correct.
When setting `HIOP_SPARSE` and `HIOP_USE_GPU`, we need to set `HIOP_USE_STRUMPACK` and check if `STRUMPACK` is available or not. This is due to the fact that `STRUMPACK` is the only sparse solver so far we can use with CUDA.
Probably we should mention "It is user's responsibility to compile STRUMP with CUDA support" in point 2.

We still can use `STRUMPACK` on CPU if we set `HIOP_SPARSE` and `HIOP_USE_STRUMPACK`, i.e., no 'HIOP_USE_GPU';

One thing I want to point out is that `cmake` will check the dependencies of `STRUMPACK`. Therefore, if we compile it with CUDA, cmake will find CUDA via STRUMPACK's configuration toolchain, no matter if we set `HIOP_USE_GPU` or not.
As a result, we can use `STRUMPACK` on GPU, but all the other HiOp code that requires `HIOP_USE_GPU=ON` will NOT be compiled.

**Comment by ashermancinelli** [comment]
I think our options have gotten too complex and we need to make some combinations unrepresentable via `cmake_dependent_option`. @nychiang I'll open a pr and I'd appreciate your suggestions there.

**Comment by cnpetra** [comment]
was this addressed by the recent cmake-related PR?

**Comment by ashermancinelli** [comment]
This can probably be closed by #246 once that's merged.

**Comment by cnpetra** [comment]
closed by #246
