### ISSUE TITLE
MPI matrix multiplication fails

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/hiop#18]
For a minimal example, I setup:

![A_{M \times N} \quad X_{N \times N} \quad W_{M \times N}](https://render.githubusercontent.com/render/math?math=A_%7BM%20%5Ctimes%20N%7D%20%5Cquad%20X_%7BN%20%5Ctimes%20N%7D%20%5Cquad%20W_%7BM%20%5Ctimes%20N%7D)

such that `W` may be a clone of `A`:

```cpp
hiop::hiopMatrixDense A(M_local, N_global, partition, comm);
hiop::hiopMatrixDense X(N_global, N_global, partition, comm);
hiop::hiopMatrixDense* W = A.alloc_clone();

A.setToConstant(1.);
W.setToConstant(1.);
X.setToConstant(1.);

// Beta = 0 to just test matmul portion
A.timesMat(0., *W, 1., X);
```
I expect `W` to have all it's elements set to `N_global`:
```cpp
//     W        = 0 * W + A  * X
double expected =         1. * 1. * N_glob;
```
This succeeds when running on a single machine. When I attempt to run this in an MPI environment however, the following assertion in `timesMat_local` is thrown:
```cpp
assert(W.n_local==W.n_global && "requested multiplication should be done in parallel using timesMat");
```

**Comment by cnpetra** [comment]
on close inspection, the code should assert/not work.

The multiplication you describe should not be attempted (and is not supported) since X would be a huge matrix for large N and the underlying class only distributes the columns. 

see commit #5ba5641 for updated documentation / better assert message

commits #30d1415 and #c2c20df also highly relevant
