### ISSUE TITLE
GPU failures on Summit when using jsrun

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/hiop#272]
When building and running with the modules described by `scripts/summitVariables.sh` in branch `update-dev-workflow` (#269), none of the test drivers are able to run via jsrun with GPU computation enabled:

```console
$ jsrun -n 1 -g 1 ./tests/testVector
[NVBLAS] NVBLAS_CONFIG_FILE environment variable is set to '<snip>'
[NVBLAS] Cannot Log File 'nvblas.log'
[NVBLAS] Using devices :0
[NVBLAS] Config parsed
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    opal_init:startup:internal-failure
But I couldn't open the help file:
    /opt/ibm/spectrum_mpi/jsm_pmix/..//container/../share/openmpi/help-opal-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[<snip>] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

Using mpirun for a single process on a compute node works and all tests pass, however when we try to use multiple ranks:
```console
$ mpirun -n 2  ./build/tests/testVector
./build/tests/testVector: error while loading shared libraries: libnvblas.so.10: cannot open shared object file: No such file or directory
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
[NVBLAS] NVBLAS_CONFIG_FILE environment variable is set to '<snip>'
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[<snip>],1]
  Exit code:    127
--------------------------------------------------------------------------
```

I can confirm nvblas is on the ld lib path:
```console
$ for p in $(echo $LD_LIBRARY_PATH | tr ':' '\n'); do
  if [ -f $p/libnvblas.so.10 ]; then
    echo $p
  fi
done
/path/to/cuda/lib64
```

Modules:
```console
$ module list

Currently Loaded Modules:
  1) exasgd-autoconf-archive/2019.01.06/gcc-7.4.0-zr3h7p2       20) xalt/1.2.1
  2) exasgd-coinhsl/2015.06.23/gcc-7.4.0-k5ullmz                21) lsf-tools/2.0
  3) exasgd-gmp/6.2.1/gcc-7.4.0-6svtfvr                         22) darshan-runtime/3.1.7
  4) exasgd-hypre/2.20.0/openmpi-4.0.3/gcc-7.4.0-j2j6emj        23) DefApps
  5) exasgd-ipopt/3.12.10/gcc-7.4.0-tj6jbm2                     24) gcc/7.4.0
  6) exasgd-magma/2.5.4/cuda-10.2.89/gcc-7.4.0-mqzulie          25) cuda/10.2.89
  7) exasgd-metis/5.1.0/gcc-7.4.0-7cjo5kb                       26) m4/1.4.18
  8) exasgd-mpfr/4.1.0/gcc-7.4.0-bkusb67                        27) autoconf/2.69
  9) exasgd-openblas/0.3.15/gcc-7.4.0-i4ax3dw                   28) automake/1.16.1
 10) exasgd-parmetis/4.0.3/openmpi-4.0.3/gcc-7.4.0-ziidpag      29) zlib/1.2.11
 11) exasgd-perl/5.26.1/gcc-7.4.0-dqxsxr4                       30) pkgconf/1.5.4
 12) exasgd-petsc/3.14.6/openmpi-4.0.3/gcc-7.4.0-64pvrcl        31) readline/7.0
 13) exasgd-raja/0.12.1/cuda-10.2.89/gcc-7.4.0-bautwa2          32) hwloc/2.0.2
 14) exasgd-suite-sparse/5.10.1/gcc-7.4.0-q6quoed               33) python/3.7.0
 15) exasgd-superlu-dist/6.4.0/openmpi-4.0.3/gcc-7.4.0-p3u4ud4  34) bison/3.0.5
 16) exasgd-texinfo/6.5/gcc-7.4.0-hvoep4u                       35) diffutils/3.7
 17) exasgd-umpire/4.1.2/cuda-10.2.89/gcc-7.4.0-6b24rqv         36) cmake/3.20.2
 18) exasgd-zlib/1.2.11/gcc-7.4.0-psrojaa                       37) openmpi/4.0.3
 19) hsi/5.0.2.p5                                               38) hdf5/1.10.4
```

**Comment by ashermancinelli** [comment]
This was first identified by @jwang125 when reviewing #269.

**Comment by ashermancinelli** [comment]
The only online thread I could find related to this issue are related to the mpi prefix, and they suggest passing `-prefix /path/to/mpi` to the mpirun command. The part of the warning message that says `But I couldn't open the help file` seems to refer to a spectrum-mpi installation, which may be a symptom of this prefix issue since we're using openmpi.

**Comment by rothpc** [comment]
In looking at #269 , I'm wondering if @jwang125  was trying to run from their home directory instead of under a directory on the scratch file system (e.g., $MEMBERWORK/csc359 or $PROJWORK/csc359).  Since the scripts/summitVariables.sh creates an nvblas.conf file that specifies NVBLAS_LOGFILE without an absolute path, it'll try to write the nvblas.log file to the current working directory, and if it *is* being run from the home directory - that will fail since home directories are mounted read-only on the Summit compute nodes.  @jwang125, can you confirm or deny which directory you were in when trying to run the testVectors program?

I will report the Spectrum MPI error message failure to the OLCF helpline, but have a question first.  Was the user-built OpenMPI module loaded when the jsrun command was attempted?  I'm asking because of the path reported as where the error message file was expected to be located:
/opt/ibm/spectrum_mpi/jsm_pmix/..//container/../share/openmpi/help-opal-runtime.txt
There is no .../openmpi/help-opal-runtime.txt file (no openmpi directory) but there *is* a .../spectrum_mpi/help-opal-runtime.txt file, which makes me wonder if that directory name is being dynamically constructed from something in the environment that is different between the Spectrum MPI module file and the user-built OpenMPI module file.

In general, I recommend sticking with Spectrum MPI on Summit and using jsrun as the parallel program launcher.  I suspect the user-built OpenMPI is not configured correctly to interact with the system's resource manager.

**Comment by rothpc** [comment]
@ashermancinelli - thanks for the clarification, and sorry to all for my assumptions about the situation.   I've tracked down the person who built those OpenMPI installations to understand why they exist (since Spectrum MPI is also built on OpenMPI).  He says that he built them to have an MPI that uses GDRCopy to provide better performance for small intra-node transfers, and apparently Spectrum MPI's implementation doesn't use GDRCopy.

He also says that if you're using one of those openmpi modules, you should use mpirun instead of jsrun, so I was wrong on that count too.

So back to the failure to find libnvblas when started with mpirun with multiple processes.  What is the output from running 'mpirun -np 2 set'?  Specifically, are the LD_LIBRARY_PATHs different for the two processes?  (And is this being run on a single compute node, or multiple nodes?)

**Comment by ashermancinelli** [comment]
So if we do have to use mpirun, how to we get access to a gpu since we usually need jsrun -g 1?

**Comment by ashermancinelli** [comment]
I can check the output again, but this was on a single node

**Comment by rothpc** [comment]
The builder tells me that the mpirun included with these openmpi builds have no concept of resource sets - each process sees the entire node, so other mechanisms are needed for affinity.  I don't yet know what you would need to use for this.

My simple 2 process test tells me that the environment is not automatically propagated to all ranks.  Looks like rank 0 gets the same environment as the mpirun process but rank 1 (and presumably ranks >1) do not.  This matches the symptoms reported.  One way around this is to pass '-x LD_LIBRARY_PATH' to mpirun to get ranks 1+ to get the same LD_LIBRARY_PATH as the shell that launches the MPI processes.  Another would be to have mpirun run shell scripts that load the desired modules and then exec the actual executable.  Both are awkward.

**Comment by ashermancinelli** [comment]
Yes, this is a bit awkward. I should probably just rebuild everything with spectrum mpi. Could these warnings be printed when loading that openmpi module? I'm sure lots of other users would avoid using that openmpi if they knew the implications.

**Comment by rothpc** [comment]
I've verified that passing '-x LD_LIBRARY_PATH' works to allow all ranks find their shared libraries.  And the reason that rank 0 got the desired LD_LIBRARY_PATH but rank 1 did not, is because by default mpirun creates rank 0 on the same system where it is run.  On Summit, this means the rank 0 process is created by forking the mpirun process on the batch node, not a compute node.  Rank 1 was created on the allocated compute node.  So if anyone is wanting to use these OpenMPI and work around these warts, you'd need to pass '-x LD_LIBRARY_PATH --nolocal' to mpirun.

@ashermancinelli - I have no control over the modulefiles or these installations.  You should send the request to help@olcf.ornl.gov so our user assistance people see it and it gets entered into their ticket tracking system.

**Comment by jwang125** [comment]
I can confirm I was running from my hiop directory. I'm not sure which directory bsub runs from but the error message is run from home directory through bsub -Is.

**Comment by rothpc** [comment]
@jwang125 - sorry, I was not clear enough in what I wrote.  If your hiop directory is anywhere under your home directory, it is on a file system that is mounted read only on the Summit compute nodes.  If that's the case, with the nvblas.conf file created by that scripts/summitVariables.sh script, your program will fail at initialization because it cannot create an output nvblas.log file in that file system.

To run this or any other program on Summit's compute nodes, you'll have to ensure that any output files are written to a file system that's mounted read-write.  Most likely this means $MEMBERWORK/csc359 or $PROJWORK/csc359, or a directory underneath these.  Assuming this nvblas.log file is the only file your program writes, you could change the nvblas.conf file so that its path is a path on one these writable file systems.  But in general, best practice is to have your executable and input files on these writable file systems too, and run from there.  The way to do this depends on the software - if it supports an 'install' step, you could build in a home directory and install it onto the parallel file system.  If not, you could either build in the home directory and copy the executables "manually" to the parallel file system, or build the software in the parallel file system.

Why is Summit set up this way?  The home directories are on an NFS file system.  Programs that read or write many, or large, files experience very poor performance compared to the parallel file systems that are designed for those workloads.  $MEMBERWORK and $PROJWORK are on the parallel file system.

If you put source files in $MEMBERWORK or $PROJWORK, just keep in mind the purge policies (see https://docs.olcf.ornl.gov/accounts/olcf_policy_guide.html#retention-policy).  You'd want to make sure file modifications you want to keep are periodically copied to some non-purged location (e.g., the project home directory, your own home directory, the HPSS archive, a remote Git repository, etc.).

**Comment by jwang125** [comment]
Thank you Phil. I didn't know that. Yes hiop is on my local directory. I didn't think this was an issue because I was able to run it on Summit smoothly three months ago. I think you are suggesting we put the hiop/build/ folder which has the executable in a writable directory. I will give that a try.

**Comment by ashermancinelli** [comment]
These have indeed been resolved after rebuilding with Spectrum-mpi. I've emailed the ornl help about the openmpi module available we mistakenly used.
