### ISSUE TITLE
GPU mode: accessing GPU/unified memory

### ISSUE THREAD

**Issue by kswirydo** [LLNL/hiop#323]
The goal: make cusolver interface more seamless, without brute-force cudaMemcpy calls (if compute mode is gpu).

The problem: seg fault.

What I was doing: I got rid of the line https://github.com/LLNL/hiop/blob/cameron/cusolver-rebase-dev/src/LinAlg/hiopLinSolverSparseCUSOLVER.cpp#L461 and replaced with x.copyToDev() and used drhs directly in the subsequent cuda function. But it fails (sp_status is NOT 0), and is followed by a seg fault. How do I access actual GPU (uvm?) part of the vector?

@pelesh @CameronRutherford

**Comment by CameronRutherford** [comment]
I think providing an API for using `uvm` should be something covered in a different issue FWIW.

This does seem to be a memory initialization issue, so perhaps there just needs to be some memory initialized correctly with umpire in order to avoid using CUDA directly. I'm not convinced that this will fix the bug that we are seeing though.

**Comment by cnpetra** [comment]
`rhs->local_data()` is the pointer within the GPU mem space (if `rhs` is a RAJA HiOp vector). It is allocated by Umpire. We haven't tried to pass Umpire-allocated device arrays instead of `cudaMalloc`'ed arrays to CUDA functions, but this should work.

Try to print the information that Umpire has on   `rhs->local_data()`, just to confirm that the pointer was allocated by Umpire and if it was, it is on the device (not on host or um). See helper function here [here](https://github.com/LLNL/hiop/blob/7d5d273fc4cfa28ce34777a180c43ea6a7fc4ea2/src/Utils/hiopRajaUmpireUtils.hpp#L78)

**Comment by kswirydo** [comment]
I am getting ```__not_managed_by_Umpire__``` -> this explains a few things. The question is why is this not managed by Umpire and what am I doing wrong. @cnpetra

**Comment by cnpetra** [comment]
yes, you're running the CPU default kernels. `rhs` is not a RAJA vector and `drhs` is a double pointer on host allocated via C++ `new`. That explains the crash and `__not_managed_by_Umpire__`. You need to switch HiOp to use RAJA kernels: set option `compute_mode` to `gpu` and option `mem_space` to `um` or `device`. 

Now I realize that the "seamless integration" you're targeting first needs a sparse NLP running on the device. We haven't developed such example yet. But there is a chance that `compute_mode` set to `gpu`  and `mem_space` set to `um` may work with the sparse NLP you're currently using. Not sure if CUDA will like the pointers allocated my Umpire in the `um` space though, but give it a try. If it does not work, then we need to meet and coordinate.

**Comment by cnpetra** [comment]
closing this, please feel free to reopen
