### ISSUE TITLE
Where is the string that defines the solver type defined?

### ISSUE THREAD

**Issue by shakedregev** [LLNL/hiop#351]
For example [here](https://github.com/LLNL/hiop/blob/shaked_hybrid/src/Optimization/hiopAlgFilterIPM.cpp#L1299)

I commented it out the line after which is the one in the develop branch. Presumably I can define this string somewhere so I can choose another option (like "Hybrid") as my strkkt. Is this correct? If so, does anyone know where I change it?

**Comment by cnpetra** [comment]
yes, we should at some point define an HiOp option for the  solver you're developing. I would avoid using "hybrid" since it is too generic and we also use the name compute mode option. Maybe something more specific like  "HybridCholCG".

The string should be added [here](https://github.com/LLNL/hiop/blob/0e21a81bc58e8f1f6f3955731e5637d18f3b99e5/src/Utils/hiopOptions.cpp#L770)

**Comment by shakedregev** [comment]
Thank you. As I understand, this is just defining the options. Assuming that's correct, which function chooses the option and passes it to hiopAlgFilterIPM.cpp?

**Comment by nychiang** [comment]
@shakedregev this function 
[ `hiopAlgFilterIPMNewton::decideAndCreateLinearSystem` ](https://github.com/LLNL/hiop/blob/ae3318a74e2d9737210cae81cf0a0450e03dab4f/src/Optimization/hiopAlgFilterIPM.cpp#L1274)

**Comment by cnpetra** [comment]
you can instruct HiOp to use the new option via `SetStringValue` method of hiopOptions, see [example](https://github.com/LLNL/hiop/blob/0e21a81bc58e8f1f6f3955731e5637d18f3b99e5/src/Drivers/nlpSparse_ex6_driver.cpp#L101), or by using the file `hiop.options` (see user manual).

**Comment by shakedregev** [comment]
Thank you
